name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: install-vulkan-sdk
      run: choco install vulkan-sdk
    - name: environment variable setup
      run: set PATH="%PATH%C:\VulkanSDK\1.2.182.0\Bin;"
    - name: shader compiler test
      run: glslc --version
    - name: build-debug
      run: mingw32-make -s build-debug
