name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: shader compiler test
      run: glslc --version
    - name: build-debug
      run: mingw32-make -s build-debug
    - name: cleaning
      run: mingw32-make -i -s clean
